### ISSUE TITLE
Change html_document theme

### ISSUE THREAD

**Issue by christophergandrud** [HertieDataScience/SyllabusAndLectures#32]
FYI: you can change the general theme of your html document with `theme: THEME` where `THEME` is one of: http://bootswatch.com/

For example, to use the 'flatly' theme in your header use:

``` yaml
output:
  html_document:
    theme: flatly
```
